### ISSUE TITLE
输入数值无rem候选

### ISSUE THREAD

**Issue by buerwei** [cipchk/vscode-cssrem#38]
vscode上点f1键，进入cssrem，显示命令"CSSRem: Px To Rem"导致错误 (command 'extension.cssrem' not found)[](url)

**Comment by cipchk** [comment]
@buerwei 麻烦进入开发者模式，看是否有相应的异常信息。

**Comment by joint-song** [comment]
```
[2021-07-23 23:48:30.736] [exthost] [error] Activating extension cipchk.cssrem failed due to an error:
[2021-07-23 23:48:30.736] [exthost] [error] TypeError: Cannot read property 'length' of undefined
	at loadConfigViaFile (/Users/some_user/.vscode/extensions/cipchk.cssrem-2.4.2/out/config.js:10:45)
	at Object.loadConfig (/Users/some_user/.vscode/extensions/cipchk.cssrem-2.4.2/out/config.js:45:5)
	at activate (/Users/some_user/.vscode/extensions/cipchk.cssrem-2.4.2/out/extension.js:26:14)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:14865)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:14538)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12738
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 2)
```
安装最新版本输入数字没有提示，报错信息如上。
@cipchk

**Comment by cipchk** [comment]
@joint-song 估计你可能没有打开一个项目，所以导致单个文件无法获取整个工作目录。
